#!/usr/bin/env bash

# copy-icons brave-fmgjjmmmlfnkbppncabfkddbjimcfncm-Default

sizes=(16x16 32x32 48x48 128x128 256x256 512x512)
for size in "${sizes[@]}"; do
  mkdir -p .local/share/icons/hicolor/$size/apps
  src="$HOME/.local/share/icons/hicolor/$size/apps/$1.png"
  if [[ -f "$src" ]]; then
    echo "Copying $src"
    cp $src .local/share/icons/hicolor/$size/apps/
  fi
done